Web1.4 Added code for publishing feedbacks
PSW-2020-ORG5/HealthCare-Clinic pull request #3
Opened 2020-11-08 21:38 UTC by vukkesic

Worked on publishing functionality

get non puhsed feedbacks 

pick feedback for pushing

2020-11-08 21:55 UTC, stojke13 approved these changes
Looks ok

2020-11-08 22:30 UTC, stojke13 commented on WEB_Project/Repository/UserRepo/SecretaryRepo/SecretaryRepository.cs
> +        List<Secretary> getAllFreeSecretaries(BusinessHoursModel businessHours);
Methods names not capitalized

2020-11-08 23:21 UTC, stojke13 approved these changes
Solidan kod

2020-11-08 23:21 UTC, stojke13 commented on WEB_Project/Controllers/AppReviewController.cs
> +            return Ok(result);
Prebaciti u servis

2020-11-08 23:21 UTC, milicatosic approved these changes
Ispraviti naznačene konflikte

2020-11-08 23:28 UTC, stojke13 requested changes
**Neophodno resisti konflikte**

2020-11-08 23:29 UTC, milicatosic requested changes
Neophodno je rešiti naznačene konflikte

2020-11-09 09:15 UTC, stojke13 approved these changes
Conflicts solved , looks good

2020-11-09 09:18 UTC, milicatosic approved these changes
Conflicts resolved, all looks good.

2020-11-09 09:21 UTC, merged