[GR1.3]feature:Display layers of the map
PSW-2020-ORG5/HealthCare-Clinic pull request #9
Opened 2020-12-09 21:52 UTC by IvanLecic97

Added code for displaying layers of the map, also selecting and changing them.

2020-12-09 22:07 UTC, zorica-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [(1) GR1.3Display layers of the map:3h](https://trello.com/c/chd2ezR3/16-1-gr13display-layers-of-the-map3h)

2020-12-09 22:07 UTC, zorica-s commented
![](https://github.trello.services/images/mini-trello-icon.png) [(3) GR1.4 Select and change layers:12h](https://trello.com/c/gMuLRzCJ/17-3-gr14-select-and-change-layers12h)

2020-12-11 16:14 UTC, igorroncevic requested changes

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building1Floor0.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building1Floor0.xaml.cs
> +}
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building1Floor1.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building1Floor1.xaml.cs
> +}
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building1Floor2.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building1Floor2.xaml.cs
> +}
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building2Floor0.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building2Floor0.xaml.cs
> +}
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building2Floor1.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building2Floor1.xaml.cs
> +}
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building2Floor2.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Building2Floor2.xaml.cs
> +}
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/Map.xaml.cs
> +
Delete if unnecessary.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/MainBuildingFloor2.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/MainBuildingFloor1.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 16:14 UTC, igorroncevic commented on GraphicEditor/GraphicEditor/MainBuildingFloor0.xaml.cs
> +            string path = Directory.GetParent(Directory.GetCurrentDirectory()).Parent.Parent.Parent.Parent.Parent.FullName;
This is not a very good way of getting path. If you wanted to extract project's base path, I'd suggest trying [AppDomain.BaseDirectory](https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.basedirectory?view=net-5.0). I can't guarantee it will work but it's worth trying.

2020-12-11 18:05 UTC, stojke13 commented on GraphicEditor/GraphicEditor/Building2Floor1.xaml.cs
> +        void KlikNaZgradu(object sender, MouseButtonEventArgs e)
Rename function (eng)
*in several places

2020-12-13 16:48 UTC, igorroncevic commented
This team has quit the project, so I'm closing PR.

2020-12-13 16:48 UTC, closed without merging